package com.hibernate.model;

import java.sql.Date;


/**
 * BookBorrowInfo generated by MyEclipse - Hibernate Tools
 */

public class BookBorrowInfo  implements java.io.Serializable {


    // Fields    

     private String borrowId;
     private BookReginster bookReginster;
     private DocuStuInfo docuStuInfo;
     private String bookName;
     private Double price;
     private String bookType;
     private Date borrowDate;
     private Date returnDate;
     private String czy;

    // Constructors

    /** default constructor */
    public BookBorrowInfo() {
    }

	/** minimal constructor */
    public BookBorrowInfo(String borrowId, BookReginster bookReginster) {
        this.borrowId = borrowId;
        this.bookReginster = bookReginster;
    }
    
    /** full constructor */
    public BookBorrowInfo(String borrowId, BookReginster bookReginster, DocuStuInfo docuStuInfo, String bookName, Double price, String bookType, Date borrowDate, Integer borrowCount, Date returnDate, String sts) {
        this.borrowId = borrowId;
        this.bookReginster = bookReginster;
        this.docuStuInfo = docuStuInfo;
        this.bookName = bookName;
        this.price = price;
        this.bookType = bookType;
        this.borrowDate = borrowDate;
        this.returnDate = returnDate;
    }

   
    // Property accessors

    public String getBorrowId() {
        return this.borrowId;
    }
    
    public void setBorrowId(String borrowId) {
        this.borrowId = borrowId;
    }

    public BookReginster getBookReginster() {
        return this.bookReginster;
    }
    
    public void setBookReginster(BookReginster bookReginster) {
        this.bookReginster = bookReginster;
    }

    public DocuStuInfo getDocuStuInfo() {
        return this.docuStuInfo;
    }
    
    public void setDocuStuInfo(DocuStuInfo docuStuInfo) {
        this.docuStuInfo = docuStuInfo;
    }

    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    public String getBookType() {
        return this.bookType;
    }
    
    public void setBookType(String bookType) {
        this.bookType = bookType;
    }

    public Date getBorrowDate() {
        return this.borrowDate;
    }
    
    public void setBorrowDate(Date borrowDate) {
        this.borrowDate = borrowDate;
    }

    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

	public String getCzy() {
		return czy;
	}

	public void setCzy(String czy) {
		this.czy = czy;
	}
   








}