package com.hibernate.model;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * BookReginster generated by MyEclipse - Hibernate Tools
 */

public class BookReginster  implements java.io.Serializable {


    // Fields    

     private String bookId;
     private String bookName;
     private String bookType;
     private String writer;
     private String bookConcern;
     private Date publishDate;
     private Double price;
     private Date regDate;
     private Integer bookCount;
     private String czy;
     private String remark;
     //private Set bookBorrowInfos = new HashSet(0);


    // Constructors

    /** default constructor */
    public BookReginster() {
    }

	/** minimal constructor */
    public BookReginster(String bookId) {
        this.bookId = bookId;
    }
    
    /** full constructor */
    public BookReginster(String bookId, String bookName, String bookType, String writer, String bookConcern, Date publishDate, Double price, Date regDate, Integer bookCount, String czy, String remark, Set bookBorrowInfos) {
        this.bookId = bookId;
        this.bookName = bookName;
        this.bookType = bookType;
        this.writer = writer;
        this.bookConcern = bookConcern;
        this.publishDate = publishDate;
        this.price = price;
        this.regDate = regDate;
        this.bookCount = bookCount;
        this.czy = czy;
        this.remark = remark;
//        this.bookBorrowInfos = bookBorrowInfos;
    }

   
    // Property accessors

    public String getBookId() {
        return this.bookId;
    }
    
    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookType() {
        return this.bookType;
    }
    
    public void setBookType(String bookType) {
        this.bookType = bookType;
    }

    public String getWriter() {
        return this.writer;
    }
    
    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getBookConcern() {
        return this.bookConcern;
    }
    
    public void setBookConcern(String bookConcern) {
        this.bookConcern = bookConcern;
    }

    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    public Integer getBookCount() {
        return this.bookCount;
    }
    
    public void setBookCount(Integer bookCount) {
        this.bookCount = bookCount;
    }

    public String getCzy() {
        return this.czy;
    }
    
    public void setCzy(String czy) {
        this.czy = czy;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

//    public Set getBookBorrowInfos() {
//        return this.bookBorrowInfos;
//    }
//    
//    public void setBookBorrowInfos(Set bookBorrowInfos) {
//        this.bookBorrowInfos = bookBorrowInfos;
//    }
   








}