package com.hibernate.model;

import java.sql.Date;


/**
 * CourseStuInfo generated by MyEclipse - Hibernate Tools
 */

public class CourseStuInfo  implements java.io.Serializable {


    // Fields    

     private String lsh;
     private SystemCourseCode systemCourseCode;
     private DocuStuInfo docuStuInfo;
     private Float grade;
     private String examType;
     private Date examDate;
     private String czy;


    // Constructors

    /** default constructor */
    public CourseStuInfo() {
    }

    
    /** full constructor */
    public CourseStuInfo(SystemCourseCode systemCourseCode, DocuStuInfo docuStuInfo, Float grade, String examType, Date examDate, String czy) {
        this.systemCourseCode = systemCourseCode;
        this.docuStuInfo = docuStuInfo;
        this.grade = grade;
        this.examType = examType;
        this.examDate = examDate;
        this.czy = czy;
    }

   
    // Property accessors

    public String getLsh() {
        return this.lsh;
    }
    
    public void setLsh(String lsh) {
        this.lsh = lsh;
    }

    public SystemCourseCode getSystemCourseCode() {
        return this.systemCourseCode;
    }
    
    public void setSystemCourseCode(SystemCourseCode systemCourseCode) {
        this.systemCourseCode = systemCourseCode;
    }

    public DocuStuInfo getDocuStuInfo() {
        return this.docuStuInfo;
    }
    
    public void setDocuStuInfo(DocuStuInfo docuStuInfo) {
        this.docuStuInfo = docuStuInfo;
    }

    public Float getGrade() {
        return this.grade;
    }
    
    public void setGrade(Float grade) {
        this.grade = grade;
    }

    public String getExamType() {
        return this.examType;
    }
    
    public void setExamType(String examType) {
        this.examType = examType;
    }

    public Date getExamDate() {
        return this.examDate;
    }
    
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    public String getCzy() {
        return this.czy;
    }
    
    public void setCzy(String czy) {
        this.czy = czy;
    }
   








}