package com.hibernate.model;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * DocuStuInfo generated by MyEclipse - Hibernate Tools
 */

public class DocuStuInfo  implements java.io.Serializable {


    // Fields    

     private String stuId;
     private String name;
     private String sex;
     private Integer age;
     private String sfzhm;
     private Date csrq;
     private String zzmm;
     private String jtdh;
     private String jtdz;
     private String jkzk;
     private Set courseStu = new HashSet();

// Constructors

    /** default constructor */
//    public DocuStuInfo() {
//    }
//
//	/** minimal constructor */
//    public DocuStuInfo(String stuId) {
//        this.stuId = stuId;
//    }
//    
//    /** full constructor */
//    public DocuStuInfo(String stuId, String name, String sex, Integer age, String sfzhm, Date csrq, String zzmm, String jtdh, String jtdz, String jkzk) {
//        this.stuId = stuId;
//        this.name = name;
//        this.sex = sex;
//        this.age = age;
//        this.sfzhm = sfzhm;
//        this.csrq = csrq;
//        this.zzmm = zzmm;
//        this.jtdh = jtdh;
//        this.jtdz = jtdz;
//        this.jkzk = jkzk;
//    }
    

   
    // Property accessors

    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public String getSfzhm() {
        return this.sfzhm;
    }
    
    public void setSfzhm(String sfzhm) {
        this.sfzhm = sfzhm;
    }

    public Date getCsrq() {
        return this.csrq;
    }
    
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    public String getZzmm() {
        return this.zzmm;
    }
    
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm;
    }

    public String getJtdh() {
        return this.jtdh;
    }
    
    public void setJtdh(String jtdh) {
        this.jtdh = jtdh;
    }

    public String getJtdz() {
        return this.jtdz;
    }
    
    public void setJtdz(String jtdz) {
        this.jtdz = jtdz;
    }

    public String getJkzk() {
        return this.jkzk;
    }
    
    public void setJkzk(String jkzk) {
        this.jkzk = jkzk;
    }

	public Set getCourseStu() {
		return courseStu;
	}

	public void setCourseStu(Set courseStu) {
		this.courseStu = courseStu;
	} 
}