package com.hibernate.model;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * DocuTeaInfo generated by MyEclipse - Hibernate Tools
 */

public class DocuTeaInfo  implements java.io.Serializable {


    // Fields    

     private String teaId;
     private SystemSpecialtyCode systemSpecialtyCode;
     private String name;
     private String sex;
     private Integer age;
     private String minzu;
     private String zzmm;
     private String xueli;
     private String hunfou;
     private Date csrq;
     private String sfzh;
     private String lxdh;
     private Date gzrq;
     private String gzjj;
     private Set emplAssignCourses = new HashSet(0);
     private Set emplAssignCharges = new HashSet(0);


    // Constructors

    /** default constructor */
    public DocuTeaInfo() {
    }

	/** minimal constructor */
    public DocuTeaInfo(String teaId, SystemSpecialtyCode systemSpecialtyCode) {
        this.teaId = teaId;
        this.systemSpecialtyCode = systemSpecialtyCode;
    }
    
    /** full constructor */
    public DocuTeaInfo(String teaId, SystemSpecialtyCode systemSpecialtyCode, String name, String sex, Integer age, String minzu, String zzmm, String xueli, String hunfou, Date csrq, String sfzh, String lxdh, Date gzrq, String gzjj, Set emplAssignCourses, Set emplAssignCharges) {
        this.teaId = teaId;
        this.systemSpecialtyCode = systemSpecialtyCode;
        this.name = name;
        this.sex = sex;
        this.age = age;
        this.minzu = minzu;
        this.zzmm = zzmm;
        this.xueli = xueli;
        this.hunfou = hunfou;
        this.csrq = csrq;
        this.sfzh = sfzh;
        this.lxdh = lxdh;
        this.gzrq = gzrq;
        this.gzjj = gzjj;
        this.emplAssignCourses = emplAssignCourses;
        this.emplAssignCharges = emplAssignCharges;
    }

   
    // Property accessors

    public String getTeaId() {
        return this.teaId;
    }
    
    public void setTeaId(String teaId) {
        this.teaId = teaId;
    }

    public SystemSpecialtyCode getSystemSpecialtyCode() {
        return this.systemSpecialtyCode;
    }
    
    public void setSystemSpecialtyCode(SystemSpecialtyCode systemSpecialtyCode) {
        this.systemSpecialtyCode = systemSpecialtyCode;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public String getMinzu() {
        return this.minzu;
    }
    
    public void setMinzu(String minzu) {
        this.minzu = minzu;
    }

    public String getZzmm() {
        return this.zzmm;
    }
    
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm;
    }

    public String getXueli() {
        return this.xueli;
    }
    
    public void setXueli(String xueli) {
        this.xueli = xueli;
    }

    public String getHunfou() {
        return this.hunfou;
    }
    
    public void setHunfou(String hunfou) {
        this.hunfou = hunfou;
    }

    public Date getCsrq() {
        return this.csrq;
    }
    
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    public String getSfzh() {
        return this.sfzh;
    }
    
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh;
    }

    public String getLxdh() {
        return this.lxdh;
    }
    
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh;
    }

    public Date getGzrq() {
        return this.gzrq;
    }
    
    public void setGzrq(Date gzrq) {
        this.gzrq = gzrq;
    }

    public String getGzjj() {
        return this.gzjj;
    }
    
    public void setGzjj(String gzjj) {
        this.gzjj = gzjj;
    }

    public Set getEmplAssignCourses() {
        return this.emplAssignCourses;
    }
    
    public void setEmplAssignCourses(Set emplAssignCourses) {
        this.emplAssignCourses = emplAssignCourses;
    }

    public Set getEmplAssignCharges() {
        return this.emplAssignCharges;
    }
    
    public void setEmplAssignCharges(Set emplAssignCharges) {
        this.emplAssignCharges = emplAssignCharges;
    }
   








}