package com.hibernate.model;

import java.sql.Date;


/**
 * EmplAssignCourse generated by MyEclipse - Hibernate Tools
 */

public class EmplAssignCourse  implements java.io.Serializable {


    // Fields    

     private String lsh;
     private DocuTeaInfo docuTeaInfo;
     private SystemCourseCode systemCourseCode;
     private Date rkrq;
     private Date lizhiDate;


    // Constructors

    /** default constructor */
    public EmplAssignCourse() {
    }

	/** minimal constructor */
    public EmplAssignCourse(DocuTeaInfo docuTeaInfo, SystemCourseCode systemCourseCode) {
        this.docuTeaInfo = docuTeaInfo;
        this.systemCourseCode = systemCourseCode;
    }
    
    /** full constructor */
    public EmplAssignCourse(DocuTeaInfo docuTeaInfo, SystemCourseCode systemCourseCode, Date rkrq, Date lizhiDate) {
        this.docuTeaInfo = docuTeaInfo;
        this.systemCourseCode = systemCourseCode;
        this.rkrq = rkrq;
        this.lizhiDate = lizhiDate;
    }

   
    // Property accessors

    public String getLsh() {
        return this.lsh;
    }
    
    public void setLsh(String lsh) {
        this.lsh = lsh;
    }

    public DocuTeaInfo getDocuTeaInfo() {
        return this.docuTeaInfo;
    }
    
    public void setDocuTeaInfo(DocuTeaInfo docuTeaInfo) {
        this.docuTeaInfo = docuTeaInfo;
    }

    public SystemCourseCode getSystemCourseCode() {
        return this.systemCourseCode;
    }
    
    public void setSystemCourseCode(SystemCourseCode systemCourseCode) {
        this.systemCourseCode = systemCourseCode;
    }

    public Date getRkrq() {
        return this.rkrq;
    }
    
    public void setRkrq(Date rkrq) {
        this.rkrq = rkrq;
    }

    public Date getLizhiDate() {
        return this.lizhiDate;
    }
    
    public void setLizhiDate(Date lizhiDate) {
        this.lizhiDate = lizhiDate;
    }
   








}