package com.hibernate.model;

import java.sql.Date;


/**
 * EmplAssignCharge generated by MyEclipse - Hibernate Tools
 */

public class EmplAssignCharge  implements java.io.Serializable {


    // Fields    

     private String lsh;
     private DocuTeaInfo docuTeaInfo;
     private SystemClassInfo systemClassInfo;
     private Date rzrq;
     private Date lizhiDate;


    // Constructors

    /** default constructor */
    public EmplAssignCharge() {
    }

	/** minimal constructor */
    public EmplAssignCharge(DocuTeaInfo docuTeaInfo, SystemClassInfo systemClassInfo) {
        this.docuTeaInfo = docuTeaInfo;
        this.systemClassInfo = systemClassInfo;
    }
    
    /** full constructor */
    public EmplAssignCharge(DocuTeaInfo docuTeaInfo, SystemClassInfo systemClassInfo, Date rzrq, Date lizhiDate) {
        this.docuTeaInfo = docuTeaInfo;
        this.systemClassInfo = systemClassInfo;
        this.rzrq = rzrq;
        this.lizhiDate = lizhiDate;
    }

   
    // Property accessors

    public String getLsh() {
        return this.lsh;
    }
    
    public void setLsh(String lsh) {
        this.lsh = lsh;
    }

    public DocuTeaInfo getDocuTeaInfo() {
        return this.docuTeaInfo;
    }
    
    public void setDocuTeaInfo(DocuTeaInfo docuTeaInfo) {
        this.docuTeaInfo = docuTeaInfo;
    }

    public SystemClassInfo getSystemClassInfo() {
        return this.systemClassInfo;
    }
    
    public void setSystemClassInfo(SystemClassInfo systemClassInfo) {
        this.systemClassInfo = systemClassInfo;
    }

    public Date getRzrq() {
        return this.rzrq;
    }
    
    public void setRzrq(Date rzrq) {
        this.rzrq = rzrq;
    }

    public Date getLizhiDate() {
        return this.lizhiDate;
    }
    
    public void setLizhiDate(Date lizhiDate) {
        this.lizhiDate = lizhiDate;
    }
   








}