package com.hibernate.model;



/**
 * Login generated by MyEclipse - Hibernate Tools
 */

public class Login  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String username;
     private String password;


    // Constructors

    /** default constructor */
    public Login() {
    }

    
    /** full constructor */
    public Login(String name, String username, String password) {
        this.name = name;
        this.username = username;
        this.password = password;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
   








}