package com.hibernate.model;



/**
 * SystemSpecialtyCode generated by MyEclipse - Hibernate Tools
 */

public class SystemSpecialtyCode  implements java.io.Serializable {


    // Fields    

     private String spCode;
     private String name;


    // Constructors

    /** default constructor */
    public SystemSpecialtyCode() {
    }

	/** minimal constructor */
    public SystemSpecialtyCode(String spCode) {
        this.spCode = spCode;
    }
    
    /** full constructor */
    public SystemSpecialtyCode(String spCode, String name) {
        this.spCode = spCode;
        this.name = name;
    }
    

   
    // Property accessors

    public String getSpCode() {
        return this.spCode;
    }
    
    public void setSpCode(String spCode) {
        this.spCode = spCode;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
   








}