package com.hibernate.model;

import java.util.HashSet;
import java.util.Set;


/**
 * SystemClassInfo generated by MyEclipse - Hibernate Tools
 */

public class SystemClassInfo  implements java.io.Serializable {


    // Fields    

     private String classid;
     private SystemSpecialtyCode systemSpecialtyCode;
     private SystemGradeCode systemGradeCode;
     private String classmc;


    // Constructors

    /** default constructor */
    public SystemClassInfo() {
    }

	/** minimal constructor */
    public SystemClassInfo(String classid) {
        this.classid = classid;
    }
    
    /** full constructor */
    public SystemClassInfo(String classid, SystemSpecialtyCode systemSpecialtyCode, SystemGradeCode systemGradeCode, String classmc) {
        this.classid = classid;
        this.systemSpecialtyCode = systemSpecialtyCode;
        this.systemGradeCode = systemGradeCode;
        this.classmc = classmc;
    }

   
    // Property accessors

    public String getClassid() {
        return this.classid;
    }
    
    public void setClassid(String classid) {
        this.classid = classid;
    }

    public SystemSpecialtyCode getSystemSpecialtyCode() {
        return this.systemSpecialtyCode;
    }
    
    public void setSystemSpecialtyCode(SystemSpecialtyCode systemSpecialtyCode) {
        this.systemSpecialtyCode = systemSpecialtyCode;
    }

    public SystemGradeCode getSystemGradeCode() {
        return this.systemGradeCode;
    }
    
    public void setSystemGradeCode(SystemGradeCode systemGradeCode) {
        this.systemGradeCode = systemGradeCode;
    }

    public String getClassmc() {
        return this.classmc;
    }
    
    public void setClassmc(String classmc) {
        this.classmc = classmc;
    }
}