package com.hibernate.model;



/**
 * SystemCourseCode generated by MyEclipse - Hibernate Tools
 */

public class SystemCourseCode  implements java.io.Serializable {


    // Fields    

     private String code;
     private String subject;


    // Constructors

    /** default constructor */
    public SystemCourseCode() {
    }

	/** minimal constructor */
    public SystemCourseCode(String code) {
        this.code = code;
    }
    
    /** full constructor */
    public SystemCourseCode(String code, String subject) {
        this.code = code;
        this.subject = subject;
    }
    

   
    // Property accessors

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }
   








}