package com.hibernate.model;

import java.util.HashSet;
import java.util.Set;


/**
 * SystemGradeCode generated by MyEclipse - Hibernate Tools
 */

public class SystemGradeCode  implements java.io.Serializable {


    // Fields    

     private String grCode;
     private String grName;



    // Constructors

    /** default constructor */
    public SystemGradeCode() {
    }

	/** minimal constructor */
    public SystemGradeCode(String grCode) {
        this.grCode = grCode;
    }
    
    /** full constructor */
    public SystemGradeCode(String grCode, String grName) {
        this.grCode = grCode;
        this.grName = grName;
       
    }
    

   
    // Property accessors

    public String getGrCode() {
        return this.grCode;
    }
    
    public void setGrCode(String grCode) {
        this.grCode = grCode;
    }

    public String getGrName() {
        return this.grName;
    }
    
    public void setGrName(String grName) {
        this.grName = grName;
    }  
    
}